--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Create Database CMS
CREATE DATABASE CMS;

-- Open CMS Database
\c cms;

--
-- Name: delete_pending_records(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.delete_pending_records() RETURNS void
    LANGUAGE plpgsql
    AS $$
DECLARE
    current_date_time TIMESTAMP := NOW();
    one_week_interval INTERVAL := INTERVAL '1 week';
BEGIN
    UPDATE PLOT
    SET plot_status = 'Available'
    WHERE plot_id IN (
        SELECT p.plot_id
        FROM PLOT p
        INNER JOIN TRANSACTION t ON p.plot_id = t.plot_id
        WHERE t.trans_status = 'Pending'
        AND t.trans_date < current_date_time - one_week_interval
    ) AND plot_id NOT IN (
        SELECT p.plot_id
        FROM TRANSACTION t
        INNER JOIN PLOT p ON p.plot_id = t.plot_id
        WHERE t.trans_type = 'Booked'
    );

    DELETE FROM RELATIVE
    WHERE rel_id IN (
        SELECT r.rel_id
        FROM RELATIVE r
        INNER JOIN TRANSACTION t ON r.rel_id = t.rel_id
        WHERE t.trans_status = 'Pending'
        AND t.trans_date < current_date_time - one_week_interval
    ) AND rel_id NOT IN (
        SELECT r.rel_id
        FROM TRANSACTION t
        INNER JOIN RELATIVE r ON r.rel_id = t.rel_id
        WHERE t.trans_type = 'Booked'
    );

    UPDATE TRANSACTION
    SET trans_status = 'Cancelled'
    WHERE trans_status = 'Pending'
    AND trans_date < current_date_time - one_week_interval;
END;
$$;


ALTER FUNCTION public.delete_pending_records() OWNER TO postgres;

--
-- Name: update_rel_date_exhumation(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_rel_date_exhumation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.rel_date_exhumation := NEW.rel_date_interment + INTERVAL '5 years';
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.update_rel_date_exhumation() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: plot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plot (
    plot_id character varying(30) GENERATED ALWAYS AS ((((plot_yard)::text || (plot_row)::text) || ((plot_col)::character varying)::text)) STORED NOT NULL,
    plot_col integer NOT NULL,
    plot_row character varying(30) NOT NULL,
    plot_yard character varying(30) NOT NULL,
    plot_status character varying(30) NOT NULL,
    plot_date timestamp without time zone
);


ALTER TABLE public.plot OWNER TO postgres;

--
-- Name: record; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.record (
    rec_id integer NOT NULL,
    rec_lastpay_date timestamp without time zone NOT NULL,
    rec_lastpay_amount numeric(8,2) NOT NULL,
    rec_status character varying(30) NOT NULL,
    plot_id character varying(30),
    rel_id integer,
    user_id integer
);


ALTER TABLE public.record OWNER TO postgres;

--
-- Name: record_rec_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.record ALTER COLUMN rec_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.record_rec_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 1000000
    CACHE 1
);


--
-- Name: relative; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.relative (
    rel_id integer NOT NULL,
    rel_fname character varying(30) NOT NULL,
    rel_mname character varying(30) NOT NULL,
    rel_lname character varying(30) NOT NULL,
    rel_dob date NOT NULL,
    rel_date_death date NOT NULL,
    rel_date_interment date NOT NULL,
    rel_date_exhumation date NOT NULL,
    user_id integer
);


ALTER TABLE public.relative OWNER TO postgres;

--
-- Name: relative_rel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.relative ALTER COLUMN rel_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relative_rel_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 1000000
    CACHE 1
);


--
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    trans_id integer NOT NULL,
    trans_type character varying(10) NOT NULL,
    trans_status character varying(10) NOT NULL,
    trans_date timestamp without time zone NOT NULL,
    user_id integer,
    rel_id integer,
    plot_id character varying(30)
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- Name: transaction_trans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN trans_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_trans_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 1000000
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_fname character varying(30) NOT NULL,
    user_mname character varying(30) NOT NULL,
    user_lname character varying(30) NOT NULL,
    user_number character varying(30) NOT NULL,
    user_email character varying(30) NOT NULL,
    user_username character varying(30) NOT NULL,
    user_password character varying(30) NOT NULL,
    user_is_admin boolean DEFAULT false NOT NULL,
    user_created_at timestamp without time zone NOT NULL,
    user_updated_at timestamp without time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 100
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 1000000
    CACHE 1
);


--
-- Data for Name: plot; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plot (plot_col, plot_row, plot_yard, plot_status, plot_date) FROM stdin;
1	A	San Bartolome	Available	2023-06-20 10:16:09.372784
2	A	San Bartolome	Available	2023-06-20 10:16:09.372784
3	A	San Bartolome	Available	2023-06-20 10:16:09.372784
4	A	San Bartolome	Available	2023-06-20 10:16:09.372784
5	A	San Bartolome	Available	2023-06-20 10:16:09.372784
6	A	San Bartolome	Available	2023-06-20 10:16:09.372784
7	A	San Bartolome	Available	2023-06-20 10:16:09.372784
8	A	San Bartolome	Available	2023-06-20 10:16:09.372784
9	A	San Bartolome	Available	2023-06-20 10:16:09.372784
10	A	San Bartolome	Available	2023-06-20 10:16:09.372784
1	B	San Bartolome	Available	2023-06-20 10:16:09.372784
2	B	San Bartolome	Available	2023-06-20 10:16:09.372784
3	B	San Bartolome	Available	2023-06-20 10:16:09.372784
4	B	San Bartolome	Available	2023-06-20 10:16:09.372784
5	B	San Bartolome	Available	2023-06-20 10:16:09.372784
6	B	San Bartolome	Available	2023-06-20 10:16:09.372784
7	B	San Bartolome	Available	2023-06-20 10:16:09.372784
8	B	San Bartolome	Available	2023-06-20 10:16:09.372784
9	B	San Bartolome	Available	2023-06-20 10:16:09.372784
10	B	San Bartolome	Available	2023-06-20 10:16:09.372784
1	C	San Bartolome	Available	2023-06-20 10:16:09.372784
2	C	San Bartolome	Available	2023-06-20 10:16:09.372784
3	C	San Bartolome	Available	2023-06-20 10:16:09.372784
4	C	San Bartolome	Available	2023-06-20 10:16:09.372784
5	C	San Bartolome	Available	2023-06-20 10:16:09.372784
6	C	San Bartolome	Available	2023-06-20 10:16:09.372784
7	C	San Bartolome	Available	2023-06-20 10:16:09.372784
8	C	San Bartolome	Available	2023-06-20 10:16:09.372784
9	C	San Bartolome	Available	2023-06-20 10:16:09.372784
10	C	San Bartolome	Available	2023-06-20 10:16:09.372784
1	D	San Bartolome	Available	2023-06-20 10:16:09.372784
2	D	San Bartolome	Available	2023-06-20 10:16:09.372784
3	D	San Bartolome	Available	2023-06-20 10:16:09.372784
4	D	San Bartolome	Available	2023-06-20 10:16:09.372784
5	D	San Bartolome	Available	2023-06-20 10:16:09.372784
6	D	San Bartolome	Available	2023-06-20 10:16:09.372784
7	D	San Bartolome	Available	2023-06-20 10:16:09.372784
8	D	San Bartolome	Available	2023-06-20 10:16:09.372784
9	D	San Bartolome	Available	2023-06-20 10:16:09.372784
10	D	San Bartolome	Available	2023-06-20 10:16:09.372784
1	E	San Bartolome	Available	2023-06-20 10:16:09.372784
2	E	San Bartolome	Available	2023-06-20 10:16:09.372784
3	E	San Bartolome	Available	2023-06-20 10:16:09.372784
4	E	San Bartolome	Available	2023-06-20 10:16:09.372784
5	E	San Bartolome	Available	2023-06-20 10:16:09.372784
6	E	San Bartolome	Available	2023-06-20 10:16:09.372784
7	E	San Bartolome	Available	2023-06-20 10:16:09.372784
8	E	San Bartolome	Available	2023-06-20 10:16:09.372784
9	E	San Bartolome	Available	2023-06-20 10:16:09.372784
10	E	San Bartolome	Available	2023-06-20 10:16:09.372784
1	A	San Isidro	Available	2023-06-20 10:16:09.372784
2	A	San Isidro	Available	2023-06-20 10:16:09.372784
3	A	San Isidro	Available	2023-06-20 10:16:09.372784
4	A	San Isidro	Available	2023-06-20 10:16:09.372784
5	A	San Isidro	Available	2023-06-20 10:16:09.372784
6	A	San Isidro	Available	2023-06-20 10:16:09.372784
7	A	San Isidro	Available	2023-06-20 10:16:09.372784
8	A	San Isidro	Available	2023-06-20 10:16:09.372784
9	A	San Isidro	Available	2023-06-20 10:16:09.372784
10	A	San Isidro	Available	2023-06-20 10:16:09.372784
1	B	San Isidro	Available	2023-06-20 10:16:09.372784
2	B	San Isidro	Available	2023-06-20 10:16:09.372784
3	B	San Isidro	Available	2023-06-20 10:16:09.372784
4	B	San Isidro	Available	2023-06-20 10:16:09.372784
5	B	San Isidro	Available	2023-06-20 10:16:09.372784
6	B	San Isidro	Available	2023-06-20 10:16:09.372784
7	B	San Isidro	Available	2023-06-20 10:16:09.372784
8	B	San Isidro	Available	2023-06-20 10:16:09.372784
9	B	San Isidro	Available	2023-06-20 10:16:09.372784
10	B	San Isidro	Available	2023-06-20 10:16:09.372784
1	C	San Isidro	Available	2023-06-20 10:16:09.372784
2	C	San Isidro	Available	2023-06-20 10:16:09.372784
3	C	San Isidro	Available	2023-06-20 10:16:09.372784
4	C	San Isidro	Available	2023-06-20 10:16:09.372784
5	C	San Isidro	Available	2023-06-20 10:16:09.372784
6	C	San Isidro	Available	2023-06-20 10:16:09.372784
7	C	San Isidro	Available	2023-06-20 10:16:09.372784
8	C	San Isidro	Available	2023-06-20 10:16:09.372784
9	C	San Isidro	Available	2023-06-20 10:16:09.372784
10	C	San Isidro	Available	2023-06-20 10:16:09.372784
1	D	San Isidro	Available	2023-06-20 10:16:09.372784
2	D	San Isidro	Available	2023-06-20 10:16:09.372784
3	D	San Isidro	Available	2023-06-20 10:16:09.372784
4	D	San Isidro	Available	2023-06-20 10:16:09.372784
5	D	San Isidro	Available	2023-06-20 10:16:09.372784
6	D	San Isidro	Available	2023-06-20 10:16:09.372784
7	D	San Isidro	Available	2023-06-20 10:16:09.372784
8	D	San Isidro	Available	2023-06-20 10:16:09.372784
9	D	San Isidro	Available	2023-06-20 10:16:09.372784
10	D	San Isidro	Available	2023-06-20 10:16:09.372784
1	E	San Isidro	Available	2023-06-20 10:16:09.372784
2	E	San Isidro	Available	2023-06-20 10:16:09.372784
3	E	San Isidro	Available	2023-06-20 10:16:09.372784
4	E	San Isidro	Available	2023-06-20 10:16:09.372784
5	E	San Isidro	Available	2023-06-20 10:16:09.372784
6	E	San Isidro	Available	2023-06-20 10:16:09.372784
7	E	San Isidro	Available	2023-06-20 10:16:09.372784
8	E	San Isidro	Available	2023-06-20 10:16:09.372784
9	E	San Isidro	Available	2023-06-20 10:16:09.372784
10	E	San Isidro	Available	2023-06-20 10:16:09.372784
1	A	San Pablo	Available	2023-06-20 10:16:09.372784
2	A	San Pablo	Available	2023-06-20 10:16:09.372784
3	A	San Pablo	Available	2023-06-20 10:16:09.372784
4	A	San Pablo	Available	2023-06-20 10:16:09.372784
5	A	San Pablo	Available	2023-06-20 10:16:09.372784
6	A	San Pablo	Available	2023-06-20 10:16:09.372784
7	A	San Pablo	Available	2023-06-20 10:16:09.372784
8	A	San Pablo	Available	2023-06-20 10:16:09.372784
9	A	San Pablo	Available	2023-06-20 10:16:09.372784
10	A	San Pablo	Available	2023-06-20 10:16:09.372784
1	B	San Pablo	Available	2023-06-20 10:16:09.372784
2	B	San Pablo	Available	2023-06-20 10:16:09.372784
3	B	San Pablo	Available	2023-06-20 10:16:09.372784
4	B	San Pablo	Available	2023-06-20 10:16:09.372784
5	B	San Pablo	Available	2023-06-20 10:16:09.372784
6	B	San Pablo	Available	2023-06-20 10:16:09.372784
7	B	San Pablo	Available	2023-06-20 10:16:09.372784
8	B	San Pablo	Available	2023-06-20 10:16:09.372784
9	B	San Pablo	Available	2023-06-20 10:16:09.372784
10	B	San Pablo	Available	2023-06-20 10:16:09.372784
1	C	San Pablo	Available	2023-06-20 10:16:09.372784
2	C	San Pablo	Available	2023-06-20 10:16:09.372784
3	C	San Pablo	Available	2023-06-20 10:16:09.372784
4	C	San Pablo	Available	2023-06-20 10:16:09.372784
5	C	San Pablo	Available	2023-06-20 10:16:09.372784
6	C	San Pablo	Available	2023-06-20 10:16:09.372784
7	C	San Pablo	Available	2023-06-20 10:16:09.372784
8	C	San Pablo	Available	2023-06-20 10:16:09.372784
9	C	San Pablo	Available	2023-06-20 10:16:09.372784
10	C	San Pablo	Available	2023-06-20 10:16:09.372784
1	D	San Pablo	Available	2023-06-20 10:16:09.372784
2	D	San Pablo	Available	2023-06-20 10:16:09.372784
3	D	San Pablo	Available	2023-06-20 10:16:09.372784
4	D	San Pablo	Available	2023-06-20 10:16:09.372784
5	D	San Pablo	Available	2023-06-20 10:16:09.372784
6	D	San Pablo	Available	2023-06-20 10:16:09.372784
7	D	San Pablo	Available	2023-06-20 10:16:09.372784
8	D	San Pablo	Available	2023-06-20 10:16:09.372784
9	D	San Pablo	Available	2023-06-20 10:16:09.372784
10	D	San Pablo	Available	2023-06-20 10:16:09.372784
1	E	San Pablo	Available	2023-06-20 10:16:09.372784
2	E	San Pablo	Available	2023-06-20 10:16:09.372784
3	E	San Pablo	Available	2023-06-20 10:16:09.372784
4	E	San Pablo	Available	2023-06-20 10:16:09.372784
5	E	San Pablo	Available	2023-06-20 10:16:09.372784
6	E	San Pablo	Available	2023-06-20 10:16:09.372784
7	E	San Pablo	Available	2023-06-20 10:16:09.372784
8	E	San Pablo	Available	2023-06-20 10:16:09.372784
9	E	San Pablo	Available	2023-06-20 10:16:09.372784
10	E	San Pablo	Available	2023-06-20 10:16:09.372784
1	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
2	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
3	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
4	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
5	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
6	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
7	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
8	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
9	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
10	A	Sta. Monica	Available	2023-06-20 10:16:09.372784
1	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
2	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
3	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
4	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
5	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
6	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
7	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
8	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
9	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
10	B	Sta. Monica	Available	2023-06-20 10:16:09.372784
1	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
2	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
3	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
4	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
5	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
6	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
7	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
8	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
9	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
10	C	Sta. Monica	Available	2023-06-20 10:16:09.372784
1	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
2	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
3	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
4	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
5	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
6	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
7	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
8	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
9	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
10	D	Sta. Monica	Available	2023-06-20 10:16:09.372784
1	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
2	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
3	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
4	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
5	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
6	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
7	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
8	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
9	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
10	E	Sta. Monica	Available	2023-06-20 10:16:09.372784
1	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
2	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
3	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
4	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
5	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
6	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
7	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
8	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
9	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
10	A	Sta. Maria	Available	2023-06-20 10:16:09.372784
1	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
2	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
3	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
4	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
5	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
6	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
7	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
8	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
9	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
10	B	Sta. Maria	Available	2023-06-20 10:16:09.372784
1	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
2	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
3	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
4	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
5	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
6	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
7	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
8	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
9	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
10	C	Sta. Maria	Available	2023-06-20 10:16:09.372784
1	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
2	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
3	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
4	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
5	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
6	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
7	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
8	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
9	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
10	D	Sta. Maria	Available	2023-06-20 10:16:09.372784
1	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
2	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
3	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
4	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
5	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
6	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
7	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
8	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
9	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
10	E	Sta. Maria	Available	2023-06-20 10:16:09.372784
\.


--
-- Data for Name: record; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.record (rec_id, rec_lastpay_date, rec_lastpay_amount, rec_status, plot_id, rel_id, user_id) FROM stdin;
\.


--
-- Data for Name: relative; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.relative (rel_id, rel_fname, rel_mname, rel_lname, rel_dob, rel_date_death, rel_date_interment, rel_date_exhumation, user_id) FROM stdin;
\.


--
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaction (trans_id, trans_type, trans_status, trans_date, user_id, rel_id, plot_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, user_fname, user_mname, user_lname, user_number, user_email, user_username, user_password, user_is_admin, user_created_at, user_updated_at) FROM stdin;
100	Admin		Cemasys	09760961509	admin@cemasys.com	admin	admin	t	2023-06-20 10:20:35.248408	2023-06-20 10:20:35.248408
\.


--
-- Name: record_rec_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.record_rec_id_seq', 100, false);


--
-- Name: relative_rel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.relative_rel_id_seq', 100, false);


--
-- Name: transaction_trans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_trans_id_seq', 100, false);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 100, true);


--
-- Name: plot plot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plot
    ADD CONSTRAINT plot_pkey PRIMARY KEY (plot_id);


--
-- Name: record record_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.record
    ADD CONSTRAINT record_pkey PRIMARY KEY (rec_id);


--
-- Name: relative relative_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relative
    ADD CONSTRAINT relative_pkey PRIMARY KEY (rel_id);


--
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (trans_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: relative trgr_update_rel_date_exhumation; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trgr_update_rel_date_exhumation BEFORE INSERT ON public.relative FOR EACH ROW EXECUTE FUNCTION public.update_rel_date_exhumation();


--
-- Name: record record_plot_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.record
    ADD CONSTRAINT record_plot_id_fkey FOREIGN KEY (plot_id) REFERENCES public.plot(plot_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: record record_rel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.record
    ADD CONSTRAINT record_rel_id_fkey FOREIGN KEY (rel_id) REFERENCES public.relative(rel_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: record record_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.record
    ADD CONSTRAINT record_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: relative relative_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relative
    ADD CONSTRAINT relative_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE;


--
-- Name: transaction transaction_plot_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_plot_id_fkey FOREIGN KEY (plot_id) REFERENCES public.plot(plot_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: transaction transaction_rel_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_rel_id_fkey FOREIGN KEY (rel_id) REFERENCES public.relative(rel_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: transaction transaction_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

